// hyprsettings.test.mjs — catalog, answer parsing, Lua rendering, change semantics.
import { strict as assert } from "node:assert"
import {
  CATALOG, valueFromAnswer, batchArg, luaTable, nestPairs, evalCall,
  renderManagedLua, isChanged, changedKeys, validStore, settingFor,
} from "./hyprsettings.mjs"

let n = 0
function ok(name, fn) { fn(); n++; console.log("  ok " + name) }

// ── catalog sanity ──────────────────────────────────────────────────────────
ok("catalog keys unique", () => {
  const keys = CATALOG.map(d => d.key)
  assert.equal(new Set(keys).size, keys.length)
})
ok("catalog keywords unique", () => {
  const kw = CATALOG.map(d => d.keyword)
  assert.equal(new Set(kw).size, kw.length)
})
ok("settingFor hit + miss", () => {
  assert.equal(settingFor("blur").keyword, "decoration:blur:enabled")
  assert.equal(settingFor("nope"), null)
})

// ── valueFromAnswer ─────────────────────────────────────────────────────────
ok("bool reads the bool field", () => {
  assert.equal(valueFromAnswer({ option: "x", bool: false, set: true }, "bool"), false)
  assert.equal(valueFromAnswer({ option: "x", bool: true, set: true }, "bool"), true)
})
ok("bool falls back to int on legacy builds (0 stays off)", () => {
  assert.equal(valueFromAnswer({ option: "x", int: 0 }, "bool"), false)
  assert.equal(valueFromAnswer({ option: "x", int: 1 }, "bool"), true)
})
ok("css reads the first side of the box", () => {
  assert.equal(valueFromAnswer({ css: "5 5 5 5" }, "css"), 5)
  assert.equal(valueFromAnswer({ css: "10 10 10 10" }, "css"), 10)
})
ok("float rounds to 3 decimals", () => {
  assert.equal(valueFromAnswer({ float: 1.000000 }, "float"), 1)
  assert.equal(valueFromAnswer({ float: 0.8500000001 }, "float"), 0.85)
})
ok("missing answer reads undefined, never a fallback number", () => {
  assert.equal(valueFromAnswer(null, "int"), undefined)
  assert.equal(valueFromAnswer("error: garbage", "int"), undefined)
})

// ── batch + lua shapes ──────────────────────────────────────────────────────
ok("batchArg joins getoptions", () => {
  assert.equal(batchArg(["a:b", "c:d"]), "getoption a:b ; getoption c:d")
})
ok("luaTable nests the keyword path", () => {
  assert.equal(luaTable("decoration:blur:size", 4),
    "{ decoration = { blur = { size = 4 } } }")
})
ok("bool renders as Lua boolean, not string", () => {
  assert.equal(luaTable("decoration:blur:enabled", true),
    "{ decoration = { blur = { enabled = true } } }")
})
ok("nestPairs merges sibling paths into one table", () => {
  const nested = nestPairs([
    { keyword: "decoration:blur:enabled", value: true },
    { keyword: "decoration:blur:size", value: 8 },
    { keyword: "general:gaps_in", value: 5 },
  ])
  assert.deepEqual(nested, {
    decoration: { blur: { enabled: true, size: 8 } },
    general: { gaps_in: 5 },
  })
})
ok("evalCall flattens to a single line", () => {
  assert.equal(
    evalCall([{ keyword: "general:gaps_in", value: 5 }]),
    "hl.config({ general = { gaps_in = 5 } })")
})

// ── renderManagedLua ────────────────────────────────────────────────────────
ok("empty store renders the header only (created on first write)", () => {
  const out = renderManagedLua({})
  assert.match(out, /^-- Generated by velocity/)
  assert.ok(!out.includes("hl.config"))
})
ok("overrides render in catalog order, deterministically", () => {
  const a = renderManagedLua({ gapsIn: 8, blur: true, rounding: 4 })
  const b = renderManagedLua({ rounding: 4, blur: true, gapsIn: 8 })
  assert.equal(a, b)
})
ok("two blur keys share one table", () => {
  const out = renderManagedLua({ blur: true, blurSize: 8 })
  assert.equal((out.match(/hl\.config/g) || []).length, 1)
  assert.ok(out.includes("blur = {\n    enabled = true,\n    size = 8,"))
})
ok("no store key is quoted as a string", () => {
  const out = renderManagedLua({ gapsIn: 0, shadows: false, activeOpacity: 0.9 })
  assert.ok(!out.includes('"'))
})

// ── change semantics ────────────────────────────────────────────────────────
ok("override differing from original is changed", () => {
  assert.equal(isChanged({ gapsIn: 8 }, { gapsIn: 5 }, "gapsIn"), true)
})
ok("override equal to original is NOT changed (flip-and-flip-back)", () => {
  assert.equal(isChanged({ gapsIn: 5 }, { gapsIn: 5 }, "gapsIn"), false)
})
ok("no override is never changed, even with an original", () => {
  assert.equal(isChanged({}, { gapsIn: 5 }, "gapsIn"), false)
})
ok("override with no original stays marked until reset once", () => {
  assert.equal(isChanged({ gapsIn: 5 }, {}, "gapsIn"), true)
})
ok("changedKeys walks only overrides", () => {
  assert.deepEqual(changedKeys({ gapsIn: 8, blur: false }, { gapsIn: 8, blur: true }), ["blur"])
})

// ── store validation ────────────────────────────────────────────────────────
ok("validStore keeps in-catalog values and drops the rest", () => {
  const { overrides, originals } = validStore({
    overrides: { gapsIn: 8, ghost: 1 },
    originals: { gapsIn: 5, blurSize: 99 },
  })
  assert.deepEqual(overrides, { gapsIn: 8 })
  assert.deepEqual(originals, { gapsIn: 5 })
})
ok("validStore rejects wrong types and off-list choices", () => {
  assert.deepEqual(validStore({ overrides: { blur: 1 } }).overrides, {})
  assert.deepEqual(validStore({ overrides: { gapsIn: 7 } }).overrides, {})
  assert.deepEqual(validStore({ overrides: { blurSize: 999 } }).overrides, {})
})
ok("validStore survives garbage input", () => {
  assert.deepEqual(validStore(null), { overrides: {}, originals: {} })
  assert.deepEqual(validStore("nonsense"), { overrides: {}, originals: {} })
})

console.log("hyprsettings: " + n + " assertions passed")
