// =============================================================================
// MonitorService.qml — read-only monitor topology (hyprctl monitors -j)
// =============================================================================
// Polls `hyprctl monitors -j` and exposes a structured `monitors[]`. Read-only:
// runtime monitor reconfiguration is NOT possible on this build —
//   • `hyprctl keyword monitor …` → "keyword can't work with non-legacy parsers"
//   • `hyprctl eval …` expects Hyprlang/Lua, not a config line
//   • `hyprctl dispatch …` is routed through the Lua wrapper and errors
// (This Hyprland config is Lua-generated by a binary wrapper, so monitor mode/
// scale are set only in the Lua source / the monitor's OSD.) The Display section
// therefore shows real topology as status, with no live setters.
//
// monitors[] entry:
//   { name, desc, make, model, w, h, refreshHz, scale, vrr, dpms, transform,
//     format, colorPreset, physW, physH, modes: [{w,h,hz}] }
// `modes` is parsed from the space-separated `availableModes` string.
// =============================================================================

pragma Singleton

import QtQuick
import Quickshell.Io
import "../config" as Config

Item {
    id: root
    visible: false

    property var monitors: []

    // The focused monitor (fallback: the first). Drives the status card.
    readonly property var primary: {
        var ms = root.monitors
        for (var i = 0; i < ms.length; i++) if (ms[i].focused) return ms[i]
        return ms.length > 0 ? ms[0] : null
    }

    // -------------------------------------------------------------------------
    // POLL — hyprctl monitors -j (JSON). Slow (10s): topology is effectively
    // static, but the poll is cheap and keeps dpms/VRR fresh if they change.
    // -------------------------------------------------------------------------
    Process {
        id: monProc
        command: ["hyprctl", "monitors", "-j"]
        property string buffer: ""
        stdout: SplitParser { onRead: function(data) { monProc.buffer += data } }
        onRunningChanged: {
            if (!running) {
                root.monitors = root._parseMonitors(monProc.buffer)
                monProc.buffer = ""
            }
        }
    }

    Timer {
        interval: 10000
        running: Config.SharedState.dashboardVisible   // only when the dashboard is open
        repeat: true
        triggeredOnStart: true
        onTriggered: { if (!monProc.running) monProc.running = true }
    }

    function refresh() { if (!monProc.running) monProc.running = true }

    // -------------------------------------------------------------------------
    // PARSERS
    // -------------------------------------------------------------------------

    function _parseMonitors(raw) {
        var arr = []
        try {
            var data = JSON.parse(raw || "[]")
            for (var i = 0; i < data.length; i++) {
                var m = data[i]
                arr.push({
                    name:        m.name || "",
                    desc:        m.description || "",
                    make:        m.make || "",
                    model:       m.model || "",
                    w:           m.width || 0,
                    h:           m.height || 0,
                    refreshHz:   m.refreshRate || 0,
                    scale:       m.scale || 1,
                    vrr:         !!m.vrr,
                    dpms:        !!m.dpmsStatus,
                    transform:   m.transform || 0,
                    format:      m.currentFormat || "",
                    colorPreset: m.colorManagementPreset || "",
                    physW:       m.physicalWidth || 0,
                    physH:       m.physicalHeight || 0,
                    focused:     !!m.focused,
                    modes:       root._parseModes(m.availableModes || "")
                })
            }
        } catch (e) {
            CommandService.pushLog("[display] monitors parse error: " + e, "error")
        }
        return arr
    }

    // "3840x2160@60.00Hz 3840x2160@119.88Hz 2560x1440@120.00Hz …" → [{w,h,hz}]
    function _parseModes(s) {
        var modes = []
        var re = /(\d+)x(\d+)@([\d.]+)/g
        var match
        while ((match = re.exec(s)) !== null) {
            modes.push({ w: parseInt(match[1]), h: parseInt(match[2]), hz: parseFloat(match[3]) })
        }
        // De-dup (hyprctl can repeat) + sort by pixels desc then hz desc.
        var seen = {}, uniq = []
        for (var i = 0; i < modes.length; i++) {
            var k = modes[i].w + "x" + modes[i].h + "@" + modes[i].hz
            if (!seen[k]) { seen[k] = true; uniq.push(modes[i]) }
        }
        uniq.sort(function(a, b) {
            var pa = a.w * a.h, pb = b.w * b.h
            if (pa !== pb) return pb - pa
            return b.hz - a.hz
        })
        return uniq
    }
}
